apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-comics
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 10.27.27.250
    path: /volume1/comics
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-comics
  namespace: media
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs

