apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kavita-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path  # adjust if your cluster uses another name

