apiVersion: v1
kind: PersistentVolume
metadata:
  name: foundry-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 10.27.27.250
    path: /volume1/foundry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-pvc
  namespace: foundryvtt
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs
