apiVersion: v1
kind: Service
metadata:
  name: foundry-service
  namespace: foundryvtt
spec:
  selector:
    app: foundry-vtt
  type: NodePort
  ports:
    - name: webui
      port: 30000
      targetPort: 30000
      nodePort: 32555
