# statping-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: statping
  namespace: monitoring
spec:
  selector:
    app: statping
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31001

