apiVersion: v1
kind: Service
metadata:
  name: smokeping
  namespace: monitoring
spec:
  selector:
    app: smokeping
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32002

