apiVersion: v1
kind: Service
metadata:
  name: librespeed
  namespace: monitoring
spec:
  selector:
    app: librespeed
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31002

