apiVersion: v1
kind: Service
metadata:
  name: netdata
  namespace: monitoring
spec:
  selector:
    app: netdata
  type: NodePort
  ports:
    - port: 19999
      targetPort: 19999
      nodePort: 31000

