apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-vpn
  namespace: torrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent-vpn
  template:
    metadata:
      labels:
        app: qbittorrent-vpn
    spec:
      containers:
        - name: gluetun
          image: qmcgaw/gluetun
          ports:
            - name: http-proxy
              containerPort: 8888
              protocol: TCP
            - name: tcp-shadowsocks
              containerPort: 8388
              protocol: TCP
            - name: udp-shadowsocks
              containerPort: 8388
              protocol: UDP
            - name: web-ui-input
              containerPort: 8080
              protocol: TCP
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "private internet access"
            - name: VPN_TYPE
              value: "openvpn"
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: gluetun-secret
                  key: OPENVPN_USER
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gluetun-secret
                  key: OPENVPN_PASSWORD
            - name: SERVER_REGIONS
              value: "CA Montreal"
            - name: FIREWALL_INPUT_PORTS
              value: "8080,6881"
            - name: UPDATER_PERIOD
              value: "24h"
            - name: UPDATER_VPN_SERVICE_PROVIDERS
              value: "private internet access"
            - name: BLOCK_IPV6
              value: "on"
            - name: UPDATER_PREFER_DIRECT_DOWNLOAD
              value: "yes"
          volumeMounts:
            - mountPath: /gluetun
              name: gluetun-config
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]

        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "UTC"
            - name: WEBUI_PORT
              value: "8080"
            - name: WEBUI_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gluetun-secret
                  key: WEBUI_USERNAME
            - name: WEBUI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gluetun-secret
                  key: WEBUI_PASSWORD
          volumeMounts:
            - mountPath: /config
              name: qbittorrent-config
            - mountPath: /downloads
              name: qbittorrent-downloads

      volumes:
        - name: gluetun-config
          persistentVolumeClaim:
            claimName: gluetun-config-pvc
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: qbittorrent-downloads
          persistentVolumeClaim:
            claimName: qbittorrent-nfs-pvc
