apiVersion: v1
kind: Pod
metadata:
  name: qbittorrent-edit
  namespace: torrent
spec:
  containers:
  - name: editor
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
      - name: qbittorrent-config
        mountPath: /config
  volumes:
    - name: qbittorrent-config
      persistentVolumeClaim:
        claimName: qbittorrent-config-pvc
