apiVersion: v1
kind: Service
metadata:
  name: dashy
  namespace: dashy
  labels:
    app: dashy
spec:
  type: NodePort
  selector:
    app: dashy
  ports:
    - name: http
      protocol: TCP
      port: 80           # external (service) port
      targetPort: 8080   # container port
      nodePort: 30175    # fixed node port (for LAN access)

